### GET REQUEST
GET http://localhost:8080/blogs/6441b89cf904c48614af065c


### POST REQUEST
POST http://localhost:8080/blogs/
content-type: application/json

{
  "test": "xxxxxxxxxxxxxxxxxxxxxxxxx",
  "test_1": "test"
}


### PUT REQUEST
PUT http://localhost:8080/blogs/lfybtt1z0.2gaur519tdi
content-type: application/json

{
	"hello":"world",
  "Hi":" You"
}

### DELETE REQUEST
DELETE http://localhost:8080/blogs/lg00okty0.jlagv6xyehah